### ISSUE TITLE
develop branch does not build with with LibreSSL 3.1.3 (DragonFly BSD)

### ISSUE THREAD

**Issue by tuxillo** [getdnsapi/getdns#491]
When trying to build with LibreSSL 3.1.3 on DragonFly BSD (the OS behind DPorts), we get the following error:

```
[  1%] Building C object CMakeFiles/getdns_objects.dir/src/openssl/tls.c.o
/home/user/s/getdns/src/openssl/tls.c:62:2: error: #error Configure error USE_DANESSL defined with OpenSSL 1.1 functions!
 #error Configure error USE_DANESSL defined with OpenSSL 1.1 functions!
  ^~~~~
*** Error code 1

Stop.
make[2]: stopped in /home/user/s/getdns/build
*** Error code 1

Stop.
make[1]: stopped in /home/user/s/getdns/build
*** Error code 1

Stop.
make: stopped in /home/user/s/getdns/build

```

I've also noticed that some LibreSSL support was dropped in commit 51cb57080961, does this mean that LibreSSL setups are not supported?

**Comment by tuxillo** [comment]
Any news? :)
